#
# Google+ Network Extractor
# Copyright 2011 Vincent Labatut 
#
# This file is part of Google+ Network Extractor.
# 
# Google+ Network Extractor is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
# 
# Google+ Network Extractor is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Google+ Network Extractor.  If not, see <http://www.gnu.org/licenses/>.
# 
#####################################################################################
#
# This R script uses the igraph library v0.5 to convert the edgelist and
# nodelist files generated by the Java program, into a single
# graphml file.
# Note: written for igraph v0.5
#
#####################################################################################

# init
#db.name <- "googleplus.ego"
db.name <- "googleplus.full"
path <- paste("/home/vlabatut/eclipse/workspaces/Extraction/GooglePlusParser/res/networks/",db.name,sep="")

# load edgelist
edges <- read.table(paste(path,".edgelist",sep=""),
		colClasses=c("character","character"))
# load nodelist
nodes <- read.table(paste(path,".nodelist",sep=""),
		colClasses=c("character","character","character"),
		sep="\t", quote="", row.names=1)

# build graph
library(igraph)
g <- graph.edgelist(as.matrix(edges), directed=TRUE)

# remove leaves and isolates (to go faster)
indices <- (0:(vcount(g)-1))[degree(g)>1]
g <- subgraph(graph=g, v=indices)

# display for verification
lay <- layout.fruchterman.reingold(graph=g)
plot(g,layout=lay,vertex.size=3,vertex.label=NA)

# record the graphical representation in a png file
pdf(file=paste(path,".pdf",sep=''),bg="white")
plot(g,layout=lay,vertex.size=3,vertex.label=NA)
dev.off()

# set node attributes
V(g)$firstname <- nodes[V(g)$name,1]
V(g)$lastname <- nodes[V(g)$name,2]

# save as graphml
write.graph(graph=g,file=paste(path,".graphml",sep=''),format="graphml")
